### ISSUE TITLE
Any chance for a Zygisk version of this? 

### ISSUE THREAD

**Issue by MikeZeDev** [HuskyDG/riru-integrityfix#1]
I am sure many people would be interested, not sure its possible obviously.

**Comment by HuskyDG** [comment]
It is possible and i will make it soon

**Comment by HuskyDG** [comment]
This mod of usnf might work similar https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD

**Comment by MikeZeDev** [comment]
> This mod of usnf might work similar https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD

I've seen this one on XDA. I am wondering if the changes made to the props are permanent or not. This is why i didnt tried it. I have no problems with current USNF, i just dont want to permanently spoof an older/other OS.

Your riru module is hooking into google play to change props for the request, or something like that, am i right? Thats way more difficult but safer, imho.

**Comment by HuskyDG** [comment]
@MikeZeDev work same about inject fingerprint into gms only, leave other process see original fingerprint, but mine can be changed fingerprint

**Comment by HuskyDG** [comment]
inject fingerprint through zygisk make it more detectable
