### ISSUE TITLE
Failed to open config file: Permission denied

### ISSUE THREAD

**Issue by skelletR** [HuskyDG/riru-integrityfix#5]
Failed to open config file: Permission denied 
What meaning of this? I change the fingerprint.txt with my original have my phone this (POCO/surya_eea/surya:10/QKQ1.200512.002/V12.0.8.0.QJGEUXM:user/release-keys) but seem not change because still have the default you have, why? And what happens with default fingerprint is bad for my phone Xiaomi Poco X3 NFC android 10?

![IMG_20220806_221235](https://user-images.githubusercontent.com/25982450/183263063-af297265-a6d3-488c-a98f-f851d4d2af4a.jpg)

**Comment by HuskyDG** [comment]
Zygote lacks of permission to read. Please check permission flag and selinux context of `fingerprint.txt`. It should be `644` and `u:object_r:system_file:s0`

**Comment by skelletR** [comment]
> 

Understand, 644 and 755 I have it, but the u:object_r:system_file:s0 I don't know, what exactly is it, Selinux enforce I have

**Comment by HuskyDG** [comment]
> > 
> 
> Understand, 644 and 755 I have it, but the u:object_r:system_file:s0 I don't know, what exactly is it, Selinux enforce I have

![Screenshot_20220807-165953_Material Files](https://user-images.githubusercontent.com/84650617/183285610-582b938c-ebe2-439f-b41e-de68de9bf25f.png)

**Comment by skelletR** [comment]
> > > 
> > 
> > 
> > Understand, 644 and 755 I have it, but the u:object_r:system_file:s0 I don't know, what exactly is it, Selinux enforce I have
> 
> ![Screenshot_20220807-165953_Material Files](https://user-images.githubusercontent.com/84650617/183285610-582b938c-ebe2-439f-b41e-de68de9bf25f.png)

With what program you open? I have Total commander and I only see this 

![IMG_20220807_131101](https://user-images.githubusercontent.com/25982450/183285999-bbb0aebc-ea41-4f66-af11-e3ddee1ae558.jpg)

**Comment by HuskyDG** [comment]
Material Files

**Comment by skelletR** [comment]
> Material Files

I have it, can change fingerprint.txt with my phone have it (POCO/surya_eea/surya:10/QKQ1.200512.002/V12.0.8.0.QJGEUXM:user/release-keys) and the Selinux context if put it like this effect the status of Selinux enforce?  Now my phone say the default have fingerprint.txt inside I don't know if it's good for my phone and for some apps and Google system updates read the fingerprint of phone and say other and mess up my phone

**Comment by HuskyDG** [comment]
I think zygote does have permission to read files in selinux policy. Moreover, you can try:
```
magiskpolicy --live "allow zygote system_file file read"
mahiskpolicy --live "allow zygote system_file dir search"
```

**Comment by skelletR** [comment]
> I think zygote does have permission to read files in selinux policy. Moreover, you can try:
> 
> ```
> magiskpolicy --live "allow zygote system_file file read"
> mahiskpolicy --live "allow zygote system_file dir search"
> ```

Yeah, it's working now with my original fingerprint, just not pass again the new SafetyNet, for that must always put in fingerprint.txt only old android fingerprint?

![IMG_20220804_215950](https://user-images.githubusercontent.com/25982450/183287159-ad3468b5-04d6-41b1-8f50-229fef0a27b1.jpg)

**Comment by HuskyDG** [comment]
@skelletR you must use the old fingerprint to avoid it (maybe google's blacklist)

**Comment by skelletR** [comment]
> @skelletR you must use the old fingerprint to avoid it (maybe google's blacklist)

Understand, and what happens to my phone if use olld fingerprint like this you have in fingerprint.txt? Can break camera? Or something like that? Google system updates? Etc

**Comment by HuskyDG** [comment]
> > @skelletR you must use the old fingerprint to avoid it (maybe google's blacklist)
> 
> Understand, and what happens to my phone if use old fingerprint like this you have in fingerprint.txt? Can break camera? Or something like that? Google system updates? Etc

No, it is only injecting into gms so other function should not break

**Comment by skelletR** [comment]
> > > @skelletR you must use the old fingerprint to avoid it (maybe google's blacklist)
> > 
> > 
> > Understand, and what happens to my phone if use old fingerprint like this you have in fingerprint.txt? Can break camera? Or something like that? Google system updates? Etc
> 
> No, it is only injecting into gms so other function should not break

This is good, sorry ask many questions, just want to be sure my phone not break, and the gms information if want for backup or something like this for phone? And read another fingerprint?
